spring:
  application:
    name: lab1
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password: 
  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true      
  h2:
    console:
      enabled: true       
      path: /h2          
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yaml

server:
  port: 8080